sudo: false
language: scala
scala: 2.11.8
jdk: oraclejdk8
addons:
  firefox: "47.0.1"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: sbt coverage test
after_success: sbt coverageReport coveralls
cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.m2