language: scala
sudo: false
jdk: oraclejdk8
scala: 2.11.8
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - sbt test
cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.m2